# Generated by Django 4.1.3 on 2022-11-27 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_candidate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0002_job_category_workflow_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='step',
            name='candidate',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.candidate'),
        ),
        migrations.AlterField(
            model_name='step',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='job.job'),
        ),
        migrations.DeleteModel(
            name='WorkFlow',
        ),
    ]
